"""Initial migration

Revision ID: 7959a264c2ad
Revises: 515d3c162ede
Create Date: 2023-06-26 16:28:13.591588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7959a264c2ad'
down_revision = '515d3c162ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
